language: python

cache: pip

python: 3.6

env:
  - SETTINGS_MODE=travis

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE snuclub_travis;'
  - cd backend

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run snuclub/manage.py test --settings=snuclub.settings.aws
