language: python

cache: pip

python: 3.6

env:
  - SETTINGS_MODE=travis

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE snuclub_travis;'
  - cd backend

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls

before_script:
  - cd snuclub

script:
  - coverage run manage.py test --settings=snuclub.settings.aws

after_script:
  - coveralls