sudo: required

matrix:
  include:
  - language: python

    cache: pip

    python: 3.6

    env:
      - SETTINGS_MODE=travis

    services:
      - mysql

    before_install:
      - mysql -e 'CREATE DATABASE snuclub_travis;'
      - cd backend

    install:
      - pip install -r requirements.txt
      - pip install coverage
      - pip install python-coveralls

    before_script:
      - cd snuclub

    script:
      - coverage run manage.py test --settings=snuclub.settings.aws

    after_script:
      - coveralls

  - language: node_js
    node_js: 11.0
    addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
    cache:
      npm: true
      directories:
        - frontend/node_modules
    before_install:
      - export CHROME_BIN=/usr/bin/google-chrome
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - cd frontend
    install:
      - npm install
      - npm install coveralls
      - npm install -g @angular/cli
    script:
      - ng test --code-coverage --watch false
      - ng e2e
    after_success:
      - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    after_script:
      - cd ..
