# Generated by Django 2.1.2 on 2018-11-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_post', '0001_initial'),
        ('event_post', '0001_initial'),
        ('accounts', '0002_userprofile_favorite_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='event_post.EventPost'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='promotion_post.PromotionPost'),
        ),
    ]
