# Generated by Django 2.1.2 on 2018-10-26 08:57

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('activity_type', models.IntegerField(choices=[(1, '스포츠')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.utils.RandomFileName('club/profile'))),
                ('short_description', models.TextField(blank=True)),
                ('category', models.IntegerField(choices=[(1, '')])),
                ('subcategory', models.IntegerField(choices=[(1, '')])),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile')),
                ('staff', models.ManyToManyField(related_name='staffs', to='accounts.UserProfile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('join_due_datetime', models.DateTimeField(blank=True, null=True)),
                ('join_link', models.URLField(blank=True)),
                ('site_link', models.URLField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.ManyToManyField(related_name='clubs', to='club.Tag'),
        ),
    ]
