# Generated by Django 2.1.2 on 2018-11-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0002_auto_20181103_2158'),
        ('accounts', '0002_userprofile_favorite_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('hits', models.IntegerField(default=0)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_posts', to='accounts.UserProfile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_posts', to='club.Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_post_comments', to='accounts.UserProfile')),
                ('event_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post_comments', to='event_post.EventPost')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
