# Generated by Django 2.1.2 on 2018-11-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpostcomment',
            options={},
        ),
        migrations.AddField(
            model_name='eventpostcomment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
