# Generated by Django 2.1.2 on 2018-11-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0003_auto_20181103_2203'),
        ('accounts', '0003_auto_20181103_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_questions', to='accounts.UserProfile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_questions', to='club.Club')),
                ('club_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club_qa.ClubQuestion')),
            ],
        ),
    ]
